version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: olx-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: olx_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  backend:
    image: olx-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olx-api-backend
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION=Server=db;Port=3306;Database=olx_db;Uid=root;Pwd=rootpassword;
      - JWT_SECRET_KEY=SuperSecretUltraLongSecurityKeyForOlxClone2026!
      - JWT_ACCESS_TOKEN_MINUTES=30
      - CORS_ORIGINS=http://localhost:3000,http://localhost:19006,http://localhost:4200,http://localhost
      - AUTO_APPLY_MIGRATIONS=true
      - ADMIN_EMAIL=admin@olxclone.local
      - ADMIN_PASSWORD=Admin@12345
      - ADMIN_FULL_NAME=Platform Admin
      - ADMIN_PHONE_NUMBER=9999999999
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: olx-frontend
    build:
      context: ../olx-clone
      dockerfile: Dockerfile
    container_name: olx-angular-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data:
